apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website-container
        image: vanchhai99/web_site:latest
        env:
        - name: DATABASE_NAME
          value: "web_site"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "12345678"
        - name: DATABASE_HOST
          value: "172.23.38.45"
        - name: DATABASE_PORT
          value: "3306"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort